'use client';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Environment, Lightformer, RoundedBox, useTexture, PerformanceMonitor } from '@react-three/drei';
import { Suspense, useEffect, useMemo, useRef, useState } from 'react';
import * as T from 'three';
import { director } from '@/lib/director';

function ribbon(points:number[][],width=.43){
  const curve=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)),false,'catmullrom',.45);
  const positions:number[]=[],uv:number[]=[],indices:number[]=[];
  for(let i=0;i<=144;i++){const t=i/144,p=curve.getPointAt(t),tangent=curve.getTangentAt(t),side=new T.Vector3().crossVectors(new T.Vector3(0,0,1),tangent).normalize().applyAxisAngle(tangent,Math.sin(t*Math.PI*2)*.2),face=new T.Vector3().crossVectors(tangent,side).normalize(),w=width*(.75+.25*Math.sin(Math.PI*t));for(let j=0;j<=10;j++){const a=j/10*Math.PI*2;const q=p.clone().addScaledVector(side,Math.cos(a)*w).addScaledVector(face,Math.sin(a)*.11);positions.push(q.x,q.y,q.z);uv.push(t,j/10);if(i<144&&j<10){const k=i*11+j;indices.push(k,k+11,k+1,k+1,k+11,k+12);}}}
  const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g;
}
const A=[[-1.6,-1.65,.4],[-1.35,.8,.2],[-.35,2.15,-.15],[.65,1.35,.1],[.72,-.1,.65],[-.35,-.85,.8],[-1,-.42,.62]];
const G=[[1.15,1.48,-.2],[2,.4,-.72],[1.5,-1.12,-.35],[.18,-1.78,.1],[-.7,-1.05,.26],[-.5,.1,.5],[.45,.26,.25],[1.15,-.03,.5]];

function Sculpture({position=[1.8,0,0],scale=1,still=false}:{position?:[number,number,number];scale?:number;still?:boolean}){
  const group=useRef<T.Group>(null),first=useRef<T.Group>(null),second=useRef<T.Group>(null);
  const shapes=useMemo(()=>[ribbon(A,.55),ribbon(G,.48)],[]);
  const metal=useMemo(()=>{const m=new T.MeshPhysicalMaterial({color:'#b4b1a7',metalness:.92,roughness:.24,clearcoat:.6,clearcoatRoughness:.15});m.userData.time={value:0};m.onBeforeCompile=shader=>{shader.uniforms.uSculptureTime=m.userData.time;shader.vertexShader='uniform float uSculptureTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed += normal * .012 * sin(position.y * 3.1 + uSculptureTime * .22);');};return m;},[]);
  const glass=useMemo(()=>new T.MeshPhysicalMaterial({color:'#6a7890',metalness:.25,roughness:.19,transparent:true,opacity:.28,side:T.DoubleSide,depthWrite:false}),[]);
  const seam=useMemo(()=>new T.TubeGeometry(new T.CatmullRomCurve3(G.map(p=>new T.Vector3(...p))),96,.015,5,false),[]);
  useEffect(()=>()=>{shapes.forEach(g=>g.dispose());metal.dispose();glass.dispose();seam.dispose();},[shapes,metal,glass,seam]);
  useFrame(({clock},dt)=>{if(!group.current||!first.current||!second.current)return;if(!director.reduced&&!still)metal.userData.time.value=clock.elapsedTime;const split=still||director.reduced?0:T.MathUtils.smoothstep(director.progress,0,.14);first.current.position.x=T.MathUtils.damp(first.current.position.x,-split*2,5,dt);second.current.position.x=T.MathUtils.damp(second.current.position.x,split*2,5,dt);group.current.rotation.y=T.MathUtils.damp(group.current.rotation.y,director.reduced?0:director.pointer.x*.13+Math.sin(clock.elapsedTime*.14)*.08,4,dt);group.current.rotation.z=T.MathUtils.damp(group.current.rotation.z,director.reduced?0:director.pointer.y*.04,4,dt);});
  return <group ref={group} position={position} scale={scale}><group ref={first}><mesh geometry={shapes[0]} material={metal}/><mesh geometry={shapes[0]} material={glass} scale={[.91,.97,1.06]} position={[.03,0,.12]}/></group><group ref={second}><mesh geometry={shapes[1]} material={metal}/><mesh geometry={seam}><meshBasicMaterial color="#d0c5b4" toneMapped={false}/></mesh></group><mesh position={[.0,-2.15,0]}><cylinderGeometry args={[2.1,2.4,.18,64]}/><meshStandardMaterial color="#101116" metalness={.7} roughness={.25}/></mesh></group>;
}
function SignalPanel(){
  const map=useMemo(()=>{const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=384;const c=canvas.getContext('2d')!;c.fillStyle='#10151d';c.fillRect(0,0,1024,384);c.strokeStyle='#25303a';c.lineWidth=1;for(let x=0;x<1024;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,384);c.stroke();}for(let y=0;y<384;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(1024,y);c.stroke();}c.fillStyle='#afb9c5';c.font='22px monospace';c.fillText('SIGNAL STUDY / SIMULATED DATA',40,45);c.strokeStyle='#c79861';c.lineWidth=4;c.beginPath();for(let x=30;x<995;x++){const phase=(x%170)/170;const spike=phase>.42&&phase<.47?-90*Math.sin((phase-.42)/.05*Math.PI):phase>.47&&phase<.53?155*Math.sin((phase-.47)/.06*Math.PI):phase>.53&&phase<.58?-35*Math.sin((phase-.53)/.05*Math.PI):0;const y=212+Math.sin(x*.04)*5-spike;x===30?c.moveTo(x,y):c.lineTo(x,y);}c.stroke();const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;return texture;},[]);
  useEffect(()=>()=>map.dispose(),[map]);
  return <mesh position={[1.3,1.3,-1.6]} rotation={[0,-.15,0]}><planeGeometry args={[4.3,1.62]}/><meshBasicMaterial map={map} transparent opacity={.82}/></mesh>;
}
function Health(){const group=useRef<T.Group>(null);useFrame(({clock},dt)=>{if(group.current){group.current.position.z=T.MathUtils.damp(group.current.position.z,-26+(director.hover==='healthpatch'?.5:0),4,dt);group.current.rotation.y=director.reduced?0:Math.sin(clock.elapsedTime*.18)*.07;}});return <group ref={group} position={[1.8,0,-26]}><RoundedBox args={[4.1,.4,3.1]} radius={.08} position={[0,-1.7,0]}><meshStandardMaterial color="#111217" roughness={.24} metalness={.6}/></RoundedBox><group rotation={[.28,.15,.05]}><RoundedBox args={[2.7,.24,1.7]} radius={.16}><meshPhysicalMaterial color="#bfc6c7" roughness={.23} metalness={.24} clearcoat={.8}/></RoundedBox><RoundedBox args={[2.38,.06,1.4]} radius={.12} position={[0,.15,0]}><meshPhysicalMaterial color="#465568" roughness={.19} metalness={.4}/></RoundedBox>{[-.75,0,.75].map(x=><mesh key={x} position={[x,.2,0]}><cylinderGeometry args={[.25,.25,.05,32]}/><meshStandardMaterial color="#b6a485" metalness={.85} roughness={.28}/></mesh>)}<mesh position={[0,.22,.55]}><boxGeometry args={[1.8,.015,.022]}/><meshBasicMaterial color="#c79861"/></mesh></group><SignalPanel/><mesh position={[-1.6,.8,-1.2]}><boxGeometry args={[.015,3.2,.015]}/><meshBasicMaterial color="#c79861"/></mesh></group>;}
function Atlas(){const texture=useTexture('/projects/atlas-saturn.png');const group=useRef<T.Group>(null);useFrame(({clock},dt)=>{if(group.current){group.current.rotation.y=T.MathUtils.damp(group.current.rotation.y,director.reduced?0:Math.sin(clock.elapsedTime*.11)*.06+(director.hover==='atlas'?.08:0),3,dt);group.current.position.z=T.MathUtils.damp(group.current.position.z,-40+(director.hover==='atlas'?.5:0),4,dt);}});return <group ref={group} position={[1.8,.1,-40]}><RoundedBox args={[5.7,3.45,.28]} radius={.18}><meshStandardMaterial color="#434a55" metalness={.92} roughness={.2}/></RoundedBox><mesh position={[0,0,.16]}><planeGeometry args={[5.43,3.15]}/><meshBasicMaterial map={texture}/></mesh><mesh position={[0,0,.18]}><planeGeometry args={[5.43,3.15]}/><meshPhysicalMaterial color="#adc2dc" transparent opacity={.045} metalness={.2} roughness={.1} depthWrite={false}/></mesh>{[-2.4,2.4].map(x=><mesh key={x} position={[x,3,0]}><cylinderGeometry args={[.012,.012,4.5,8]}/><meshStandardMaterial color="#545962" metalness={.8} roughness={.3}/></mesh>)}<mesh position={[0,-2.25,0]}><boxGeometry args={[4.4,.04,2.6]}/><meshStandardMaterial color="#121318" metalness={.7} roughness={.2}/></mesh></group>;}
function Mechanism(){const group=useRef<T.Group>(null);useFrame((_,dt)=>{if(group.current)group.current.rotation.y=T.MathUtils.damp(group.current.rotation.y,director.reduced?0:(director.progress-.5)*3,4,dt);});return <group ref={group} position={[1.8,0,-53]}>{[1.2,1.75,2.25].map((r,i)=><group key={r} rotation={[i*.5+.3,.2,i*.6]}><mesh><torusGeometry args={[r,.025,6,96]}/><meshStandardMaterial color="#788190" metalness={.85} roughness={.25}/></mesh>{[0,Math.PI].map(a=><mesh key={a} position={[Math.cos(a)*r,Math.sin(a)*r,0]}><boxGeometry args={[.24,.12,.16]}/><meshStandardMaterial color="#c79861" metalness={.7} roughness={.3}/></mesh>)}</group>)}<mesh rotation={[.4,.8,.2]}><octahedronGeometry args={[.7,0]}/><meshPhysicalMaterial color="#8274c8" transparent opacity={.65} metalness={.55} roughness={.16} clearcoat={1}/></mesh><pointLight color="#8274c8" intensity={3} distance={7}/></group>;}
function Timeline(){return <group position={[1.5,0,-65]}><mesh rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.014,.014,6,8]}/><meshBasicMaterial color="#b8a17f"/></mesh>{[-2.3,0,2.3].map((x,i)=><group key={x} position={[x,.0,0]}><mesh><sphereGeometry args={[.07,12,12]}/><meshBasicMaterial color={i===0?'#ece9e2':'#c79861'}/></mesh><mesh position={[0,-.55,0]}><boxGeometry args={[.014,1,.014]}/><meshStandardMaterial color="#8795a8" metalness={.8}/></mesh><RoundedBox position={[0,-1.2,0]} args={[1.6,.55,.08]} radius={.035}><meshStandardMaterial color="#1b202b" metalness={.5} roughness={.2}/></RoundedBox></group>)}</group>;}
function Branches(){const geometries=useMemo(()=>{const pairs=[[[0,-2,0],[0,1,0]],[[0,-.5,0],[-1.7,.8,.4]],[[0,.2,0],[1.5,1.4,.2]],[[0,1,0],[-.7,2.2,-.2]],[[1.5,1.4,.2],[2.2,2.1,.2]]];return pairs.map(p=>new T.TubeGeometry(new T.CatmullRomCurve3(p.map(q=>new T.Vector3(...q))),1,.04,8,false));},[]);useEffect(()=>()=>geometries.forEach(g=>g.dispose()),[geometries]);return <group position={[2,0,-78]} rotation={[.05,-.2,-.08]}>{geometries.map((g,i)=><mesh key={i} geometry={g}><meshStandardMaterial color="#6b7080" metalness={.9} roughness={.24}/></mesh>)}{[[0,-.5,0],[0,1,0],[-1.7,.8,.4],[1.5,1.4,.2],[-.7,2.2,-.2],[2.2,2.1,.2]].map((p,i)=><mesh key={i} position={p as [number,number,number]}><sphereGeometry args={[.095,16,16]}/><meshBasicMaterial color="#c79861"/></mesh>)}</group>;}
const cameraKeys=[[4.1,1.8,10],[2,.9,-5],[3.8,2.1,-17],[3.6,1,-30],[3.9,1.6,-43],[3.1,1,-56],[3.8,1.4,-69],[3.7,1.4,-83]];
const targets=[[-.3,.1,0],[1.1,0,-13],[1.8,0,-26],[1.8,0,-40],[1.8,0,-53],[1.5,0,-65],[2,0,-78],[1.6,0,-92]];
function Rig(){const {camera,size}=useThree();const target=useMemo(()=>new T.Vector3(),[]);useFrame((_,dt)=>{const p=T.MathUtils.clamp(director.progress,0,1)*7;let index=Math.min(6,Math.floor(p)),f=T.MathUtils.smoothstep(p-index,0,1);if(director.reduced){index=Math.min(6,Math.round(p));f=index===6&&p>6.5?1:0;}for(let k=0;k<3;k++){const axis=(['x','y','z'] as const)[k],offset=director.reduced?0:k===0?director.pointer.x*.22:k===1?-director.pointer.y*.12:0;camera.position[axis]=T.MathUtils.damp(camera.position[axis],T.MathUtils.lerp(targets[index][k],targets[index+1][k],f)+(T.MathUtils.lerp(cameraKeys[index][k],cameraKeys[index+1][k],f)-T.MathUtils.lerp(targets[index][k],targets[index+1][k],f))*(size.width<700?1.55:1)+offset, director.reduced?100:5,dt);target[axis]=T.MathUtils.lerp(targets[index][k],targets[index+1][k],f);}camera.lookAt(target);});return null;}
function Dust(){const positions=useMemo(()=>{const a=new Float32Array(180*3);let seed=79;for(let i=0;i<a.length;i++){seed=(seed*16807)%2147483647;a[i]=(seed/2147483647-.5)*(i%3===0?16:i%3===1?9:104)+(i%3===2?-44:0);}return a;},[]);const ref=useRef<T.Points>(null);useFrame((_,dt)=>{if(ref.current&&!director.reduced)ref.current.position.y=Math.sin(director.progress*5)*.08+Math.sin(performance.now()*.0001)*.05*dt;});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions,3]}/></bufferGeometry><pointsMaterial color="#b5aa96" size={.014} transparent opacity={.3} depthWrite={false}/></points>;}
function Room(){return <group>{Array.from({length:8},(_,i)=><group key={i} position={[0,0,-i*13]}><mesh position={[0,-2.4,0]}><boxGeometry args={[20,.12,14]}/><meshStandardMaterial color="#040508" metalness={.3} roughness={.5} envMapIntensity={.18}/></mesh>{[-6.5,6.5].map(x=><group key={x}><mesh position={[x,1,0]}><boxGeometry args={[.17,8,.24]}/><meshStandardMaterial color="#17191f" metalness={.5} roughness={.4}/></mesh><mesh position={[x-.06,1,.17]}><boxGeometry args={[.025,6,.02]}/><meshBasicMaterial color={i%3===0?'#c2b9a5':'#53677f'}/></mesh></group>)}<mesh position={[0,4.9,0]}><boxGeometry args={[13,.16,.4]}/><meshStandardMaterial color="#17191f" roughness={.5}/></mesh></group>)}</group>;}
export default function Gallery({reduced}:{reduced:boolean}){const [dpr,setDpr]=useState(.9),[visible,setVisible]=useState(true);useEffect(()=>{const change=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',change);return()=>document.removeEventListener('visibilitychange',change);},[]);return <Canvas aria-label="Interactive architectural gallery with interlocking titanium ribbons and two project installations" dpr={dpr} frameloop={visible?'always':'never'} camera={{position:[4.1,1.8,10],fov:43,near:.1,far:150}} gl={{antialias:false,powerPreference:'high-performance',alpha:false}} onCreated={({gl})=>{gl.setClearColor('#020204');gl.toneMapping=T.ACESFilmicToneMapping;gl.toneMappingExposure=1.15;}}><PerformanceMonitor onDecline={()=>setDpr(.6)} flipflops={2} onFallback={()=>setDpr(.6)}/><fog attach="fog" args={['#020204',13,42]}/><ambientLight intensity={.12}/><directionalLight position={[3,7,4]} intensity={3.5} color="#ece9e2"/><directionalLight position={[-4,3,-3]} intensity={2.2} color="#7f98b5"/><Suspense fallback={null}><Environment resolution={64} frames={1}><Lightformer color="#ece9e2" intensity={4} position={[0,5,3]} scale={[8,2,1]} rotation={[Math.PI/2,0,0]}/><Lightformer color="#8795a8" intensity={3} position={[-5,0,0]} scale={[2,7,1]} rotation={[0,Math.PI/2,0]}/><Lightformer color="#ece9e2" intensity={2.5} position={[5,1,-3]} scale={[2,5,1]} rotation={[0,-Math.PI/2,0]}/></Environment></Suspense><Rig/><Room/><Sculpture/><group position={[1.7,0,-13]}><RoundedBox args={[2.6,4,.06]} radius={.02} rotation={[0,.6,.08]}><meshPhysicalMaterial color="#65788f" transparent opacity={.16} metalness={.6} roughness={.12} depthWrite={false}/></RoundedBox></group><Health/><Suspense fallback={null}><Atlas/></Suspense><Mechanism/><Timeline/><Branches/><Sculpture position={[1.8,0,-92]} scale={.48} still/><Dust/>{reduced&&<ambientLight intensity={.03}/>}</Canvas>;}

