'use client';
import dynamic from 'next/dynamic';
import { Component, useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowUpRight, ArrowDown, Plus, X, Github, Mail, Check, MoveUpRight } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import { capabilities, chapters, education, identity, projects, type Project } from '@/lib/content';
import { director } from '@/lib/director';
import Music from './Music';
gsap.registerPlugin(ScrollTrigger);
const Gallery=dynamic(()=>import('./Gallery'),{ssr:false,loading:()=> <Fallback loading/>});
function Fallback({loading=false}:{loading?:boolean}){return <div className="gallery-fallback" aria-label={loading?'Gallery loading':'Static architectural composition'}><svg viewBox="0 0 500 600" aria-hidden="true"><defs><linearGradient id="metal"><stop stopColor="#272b35"/><stop offset=".35" stopColor="#a5abb5"/><stop offset=".46" stopColor="#ece9e2"/><stop offset=".6" stopColor="#515c6b"/><stop offset="1" stopColor="#151820"/></linearGradient></defs><path d="M100 460 Q60 240 185 115 Q265 60 290 200 Q350 365 190 395" fill="none" stroke="url(#metal)" strokeWidth="42"/><path d="M340 160 Q450 300 350 455 Q215 520 195 360 Q180 275 350 325" fill="none" stroke="url(#metal)" strokeWidth="37"/></svg><span>{loading?'PREPARING THE GALLERY':'STATIC EXPERIENCE / ALL CONTENT AVAILABLE'}</span></div>;}
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<Fallback/>:this.props.children;}}
function Tag({children}:{children:ReactNode}){return <div className="tag"><span/>{children}</div>;}
export default function Portfolio(){
  const root=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),cursor=useRef<HTMLDivElement>(null),lenis=useRef<Lenis|null>(null),returnFocus=useRef<HTMLElement|null>(null);
  const [reduced,setReduced]=useState(false),[staticMode,setStatic]=useState(false),[chapter,setChapter]=useState(0),[project,setProject]=useState<Project|null>(null),[settings,setSettings]=useState(false),[copied,setCopied]=useState(false);
  useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const change=()=>setReduced(mq.matches);mq.addEventListener('change',change);if(new URLSearchParams(location.search).get('static')==='1')setStatic(true);return()=>mq.removeEventListener('change',change);},[]);
  useEffect(()=>{director.reduced=reduced;const smooth=new Lenis({duration:1.25,smoothWheel:!reduced,anchors:true,autoRaf:false});lenis.current=smooth;const tick=(time:number)=>smooth.raf(time*1000);gsap.ticker.add(tick);smooth.on('scroll',ScrollTrigger.update);let current=-1;
    const context=gsap.context(()=>{ScrollTrigger.create({trigger:root.current,start:'top top',end:'bottom bottom',onUpdate:()=>{const sections=[...root.current!.querySelectorAll<HTMLElement>('main > section')];const y=window.scrollY;let index=0;while(index<7&&y>=sections[index+1].offsetTop)index++;const start=sections[index].offsetTop,end=index<7?sections[index+1].offsetTop:document.documentElement.scrollHeight-window.innerHeight;director.progress=(index+(index<7?Math.min(1,Math.max(0,(y-start)/Math.max(1,end-start))):0))/7;if(index!==current){current=index;setChapter(index);}}});
      if(!reduced)gsap.utils.toArray<HTMLElement>('.reveal').forEach(element=>gsap.fromTo(element,{opacity:.18,y:34,filter:'blur(5px)'},{opacity:1,y:0,filter:'blur(0px)',duration:1.1,ease:'power2.out',scrollTrigger:{trigger:element,start:'top 87%',toggleActions:'play none none reverse'}}));
    },root);const pointer=(e:PointerEvent)=>{director.pointer.x=e.clientX/innerWidth*2-1;director.pointer.y=e.clientY/innerHeight*2-1;if(cursor.current){gsap.to(cursor.current,{x:e.clientX,y:e.clientY,duration:.18,overwrite:true});cursor.current.classList.toggle('over',!!(e.target as HTMLElement).closest('a,button'));}};window.addEventListener('pointermove',pointer);return()=>{window.removeEventListener('pointermove',pointer);context.revert();gsap.ticker.remove(tick);smooth.destroy();lenis.current=null;};
  },[reduced]);
  useEffect(()=>{if(project){dialog.current?.showModal();document.body.style.overflow="hidden";lenis.current?.stop();}else{dialog.current?.close();document.body.style.overflow="";lenis.current?.start();requestAnimationFrame(()=>returnFocus.current?.focus({preventScroll:true}));}return()=>{};},[project]);
  useEffect(()=>{const pop=()=>{setProject(null);director.hover=null;};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
  const open=(p:Project,trigger:HTMLElement)=>{returnFocus.current=trigger;setProject(p);history.pushState({portfolioProject:p.id},'',`#project-${p.id}`);};
  const close=()=>{if(history.state?.portfolioProject)history.back();else setProject(null);};
  const magnetic=(e:React.PointerEvent<HTMLAnchorElement>)=>{if(reduced||!matchMedia('(pointer:fine)').matches)return;const rect=e.currentTarget.getBoundingClientRect();gsap.to(e.currentTarget,{x:(e.clientX-rect.left-rect.width/2)*.08,y:(e.clientY-rect.top-rect.height/2)*.12,duration:.4});};
  const copy=async()=>{try{await navigator.clipboard.writeText(identity.email);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{location.href=`mailto:${identity.email}`;}};
  return <div ref={root} className={`portfolio ${reduced?'reduced':''}`}>
    <a href="#main" className="skip">Skip to content</a><div className="scene" aria-hidden="true">{staticMode?<Fallback/>:<SceneBoundary><Gallery reduced={reduced}/></SceneBoundary>}</div><div className="scene-shade"/><div className="grain"/><div ref={cursor} className="custom-cursor"/>
    <header className="header"><a className="identity" href="#arrival" aria-label="Abhiradh Gorti home"><span className="logo">a<span>g</span></span><span className="identity-label">ABHIRADH GORTI<br/><small>INDEPENDENT EXPLORATIONS</small></span></a><nav aria-label="Main navigation"><a href="#healthpatch">WORK <span>02</span></a><a href="#about">ABOUT</a><a href="#contact">CONTACT <ArrowUpRight size={12}/></a></nav></header>
    <aside className="chapter-rail" aria-label="Gallery chapters">{chapters.map((name,index)=><a key={name} href={`#${['arrival','about','healthpatch','atlas','capabilities','education','code','contact'][index]}`} className={chapter===index?'active':''} aria-label={name} aria-current={chapter===index?'location':undefined}><span>{String(index+1).padStart(2,'0')}</span><i/><b>{name}</b></a>)}</aside>
    <main id="main">
      <section id="arrival" className="chapter arrival"><div className="arrival-kicker"><span className="live-dot"/> PORTFOLIO / THE LIVING MACHINE <span className="edition">VOL. 01 — SELECTED WORK</span></div><div className="hero-content"><p className="eyebrow">CSE / INTERACTIVE SYSTEMS / SELECTED WORK</p><h1>ABHIRADH<br/><span>GORTI</span><span className="name-period">.</span></h1><div className="hero-foot"><p>I build intelligent systems<br/>and immersive digital experiences.</p><a href="#healthpatch" className="round-action" aria-label="Explore selected work"><ArrowUpRight size={25}/></a></div></div><div className="hero-caption"><span>FIG. 01</span><p>INTERLOCKING INTELLIGENCE<br/><small>TITANIUM / GLASS / MOTION</small></p><i/></div><div className="section-floor"><a href="#about" className="scroll-prompt"><ArrowDown size={13}/> SCROLL TO ENTER</a><span>VIZIANAGARAM, INDIA <small>ANDHRA PRADESH / INDIA</small></span><span className="manifesto">SYSTEMS WITH INTELLIGENCE.<br/>EXPERIENCES WITH PRESENCE.</span></div></section>
      <section id="about" className="chapter about"><div className="section-content"><Tag>01 / THE PERSON BEHIND THE SYSTEM</Tag><h2 className="reveal">ENGINEERING<br/>WITH <em>IMAGINATION.</em></h2><div className="about-copy reveal"><p>I’m Abhiradh Gorti, a Computer Science and Engineering student exploring how software can connect intelligent systems, useful interfaces, and immersive experiences.</p><p>From visualizing health signals to building interactive exploration, I care about systems that work clearly and experiences that feel memorable.</p></div><div className="small-facts reveal"><span>THIRD-YEAR CSE STUDENT</span><span>VIZIANAGARAM, ANDHRA PRADESH</span></div></div><span className="wall-word" aria-hidden="true">PRESENCE</span></section>
      {projects.map(p=><section key={p.id} id={p.id} className={`chapter project-scene ${p.id}`}><div className="section-content"><Tag>{p.number} / {p.category}</Tag><h2 className="project-title reveal">{p.id==='atlas'?<>ATLAS<br/><span>UNIVERSE EXPLORER</span></>:<>HEALTH<span>PATCH</span></>}</h2><p className="project-summary reveal">{p.summary}</p><p className="project-small reveal">{p.id==='healthpatch'?'A research monitoring project exploring signal visualization, simulation, and statistical digital twins.':'An interactive exploration of planets, real catalogue stars, and reconstructed galaxies.'}</p><button className="text-action reveal" onClick={event=>open(p,event.currentTarget)} onPointerEnter={()=>director.hover=p.id} onPointerLeave={()=>director.hover=null} onFocus={()=>director.hover=p.id} onBlur={()=>director.hover=null}>ENTER THE PROJECT <Plus size={18}/></button><div className="project-footnote">{p.id==='healthpatch'?<><span className="live-dot amber"/> SIMULATED DATA / ILLUSTRATIVE INSTALLATION</>:<>ACTUAL PROJECT CAPTURE / RECONSTRUCTED VISUALIZATION</>}</div></div><span className="installation-caption">INSTALLATION {p.number}<br/>{p.id==='healthpatch'?'SIGNALS, MADE UNDERSTANDABLE.':'A WINDOW INTO ANOTHER SCALE.'}</span></section>)}
      <section id="capabilities" className="chapter capabilities"><div className="section-content"><Tag>04 / A CONNECTED PRACTICE</Tag><h2 className="reveal">PARTS OF<br/>A <em>BIGGER SYSTEM.</em></h2><p className="section-intro reveal">Curiosity is the common thread.<br/>These are the tools and foundations I explore.</p><div className="capability-list">{capabilities.map(g=><details key={g.name} className="reveal"><summary><span>{g.name}</span><p>{g.items.join(' / ')}</p><Plus size={14}/></summary><p>{g.copy}</p></details>)}</div></div></section>
      <section id="education" className="chapter education"><div className="section-content"><Tag>05 / ALWAYS IN DEVELOPMENT</Tag><h2 className="reveal">LEARNING<br/>IS <em>CONTINUOUS.</em></h2><div className="education-list">{education.map((item,index)=><article key={item.title} className="reveal"><span className="education-node">{String(index+1).padStart(2,'0')}</span><div><small>{item.subtitle}</small><h3>{item.title}</h3><p>{item.detail}</p></div></article>)}</div></div></section>
      <section id="code" className="chapter code"><div className="section-content"><Tag>06 / OPEN THE SOURCE</Tag><h2 className="reveal">EXPLORE<br/>MY <em>CODE.</em></h2><p className="section-intro reveal">The implementation behind the experience.</p><div className="repo-list">{projects.map(p=><a key={p.id} href={p.repository} target="_blank" rel="noopener noreferrer" className="reveal"><span>{p.number}</span><div>{p.name}<small>{p.repository.split('/').at(-1)}</small></div><ArrowUpRight size={20}/></a>)}</div><a className="text-action reveal" href={identity.github} target="_blank" rel="noopener noreferrer">GITHUB PROFILE <Github size={16}/></a></div></section>
      <section id="contact" className="chapter contact"><div className="contact-content"><Tag>07 / THE NEXT CHAPTER</Tag><h2 className="reveal">LET’S BUILD<br/>SOMETHING<br/><em>EXTRAORDINARY.</em></h2><p className="reveal">Have an idea worth exploring? Let’s connect.</p><a href={`mailto:${identity.email}`} className="contact-button reveal" onPointerMove={magnetic} onPointerLeave={e=>gsap.to(e.currentTarget,{x:0,y:0,duration:.4})}>{identity.email}<ArrowUpRight size={22}/></a><div className="contact-links"><button onClick={copy}>{copied?<Check size={13}/>:<Mail size={13}/>} {copied?'EMAIL COPIED':'COPY EMAIL'}</button>{identity.linkedin&&<a href={identity.linkedin} target="_blank" rel="noopener noreferrer">LINKEDIN <ArrowUpRight size={13}/></a>}<a href={identity.github} target="_blank" rel="noopener noreferrer">GITHUB <ArrowUpRight size={13}/></a>{identity.resume?<a href={identity.resume} download>DOWNLOAD RÉSUMÉ <ArrowDown size={13}/></a>:<span className="unavailable" title="The résumé PDF has not been supplied">RÉSUMÉ / AWAITING FILE</span>}</div></div><footer className="footer"><span>Abhiradh Gorti<small>Engineering ideas into experiences.</small></span><a href="#arrival">BACK TO THE SURFACE <MoveUpRight size={15}/></a><span className="footer-signature">DESIGNED AS A LIVING MACHINE.</span></footer></section>
    </main>
    <Music/><div className="view-controls"><span>{String(chapter+1).padStart(2,'0')} <i>/</i> 08 <b>{chapters[chapter]}</b></span><button aria-expanded={settings} onClick={()=>setSettings(!settings)}>VIEW OPTIONS <Plus size={12}/></button>{settings&&<div className="view-panel"><label><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/> Reduced motion</label><label><input type="checkbox" checked={staticMode} onChange={e=>setStatic(e.target.checked)}/> Static experience</label><p>Rendering adapts automatically to your device.</p></div>}</div>
    <dialog ref={dialog} className="project-dialog" aria-labelledby="project-detail-title" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===dialog.current)close();}} data-lenis-prevent><AnimatePresence>{project&&<motion.div initial={{opacity:0,y:reduced?0:20}} animate={{opacity:1,y:0}} className="detail-content"><button className="close-detail" onClick={close} autoFocus aria-label="Close project details"><X size={20}/></button><div className="detail-image"><img src={project.image} alt={project.imageNote}/><span>{project.imageNote}</span></div><div className="detail-copy"><Tag>{project.number} / {project.category}</Tag><h2 id="project-detail-title">{project.name}</h2><p className="detail-lead">{project.summary}</p><div className="detail-sections">{project.details.map(d=><article key={d.heading}><h3>{d.heading}</h3><p>{d.copy}</p></article>)}</div><div className="tech-stack">{project.stack.map(t=><span key={t}>{t}</span>)}</div><p className="implementation-status"><span/> {project.status}</p><a className="contact-button" href={project.repository} target="_blank" rel="noopener noreferrer">VIEW REPOSITORY <ArrowUpRight size={17}/></a>{project.demo&&<a className="text-action" href={project.demo} target="_blank" rel="noopener noreferrer">{project.id === 'healthpatch' ? 'INTERACTIVE SIMULATED DEMO' : 'LIVE EXPLORER'} <ArrowUpRight size={16}/></a>}</div></motion.div>}</AnimatePresence></dialog>
  </div>;
}


