export interface Project {id:'healthpatch'|'atlas';number:string;name:string;category:string;summary:string;repository:string;demo:string|null;image:string;imageNote:string;stack:string[];status:string;details:{heading:string;copy:string}[]}
export const identity={name:'Abhiradh Gorti',first:'Abhiradh',last:'Gorti',role:'Computer Science Student / Developer / Interactive Experience Builder',location:'Vizianagaram, Andhra Pradesh, India',email:'abhiradhgorti@gmail.com',github:'https://github.com/24kd1a05c3-dev',linkedin:'https://www.linkedin.com/in/abhiradh-gorti-2952b2322/' as string|null,resume:'/Abhiradh_Gorti_Resume_ATS_optimized.pdf' as string|null};
export const projects:Project[]=[
 {id:'healthpatch',number:'01',name:'HealthPatch',category:'HEALTH TECHNOLOGY',summary:'Making complex health signals understandable.',repository:'https://github.com/24kd1a05c3-dev/healthpatch',demo:'https://healthpatch.vercel.app',image:'/projects/healthpatch-device.png',imageNote:'Wearable concept artwork from the project. Illustrative; not completed hardware.',stack:['React','TypeScript','FastAPI','Python','MongoDB','Recharts'],status:'Implemented research prototype. Local verification; not clinically validated or approved for patient use.',details:[{heading:'The question',copy:'How can a monitoring interface make streams of health data easier to understand, while keeping their source and limits visible?'},{heading:'The implementation',copy:'A React interface backed by FastAPI and MongoDB. Patient-scoped access, normalized telemetry, WebSocket updates, history and replay support the monitoring workflow.'},{heading:'Simulation & digital twin',copy:'A scenario simulator and statistical twin explore signal behavior. Generated readings are explicitly simulated. Hardware integration and production provider delivery require further verification.'}]},
 {id:'atlas',number:'02',name:'Atlas Universe Explorer',category:'INTERACTIVE 3D EXPERIENCE',summary:'A change in scale. A new sense of perspective.',repository:'https://github.com/24kd1a05c3-dev/universe-explorer',demo:'https://universe-explorer-smoky.vercel.app',image:'/projects/atlas-saturn.png',imageNote:'Actual Atlas browser capture: Blender-authored Saturn geometry with real-time rings and lighting.',stack:['TypeScript','Three.js','WebGL','Vite','Blender'],status:'Working local explorer with 61,450 catalogue stars, nine galaxy destinations and Solar System navigation.',details:[{heading:'The experience',copy:'Travel from planetary surfaces to nearby catalogue stars and reconstructed galaxies. Search, orbit, free flight and cinematic journeys make astronomical scale navigable.'},{heading:'The rendering',copy:'Separate foreground and deep-space passes, camera-relative reference frames, procedural stellar photospheres and volumetric galaxy visualization. Auto quality uses a lighter galaxy LOD for smooth previews.'},{heading:'An honest universe',copy:'Star positions come from HYG; galaxy coordinates and distances from NED. Galaxy morphology and close-up stellar appearance are reconstructions. This is a visualization, not a physically complete universe simulation.'}]}
];
export const chapters=['Arrival','About','HealthPatch','Atlas','Capabilities','Education','Code','Contact'];
export const capabilities=[{name:'BUILD',items:['React','JavaScript','Node.js'],copy:'Interfaces, components, and application structure.'},{name:'DATA',items:['Python','MongoDB','Redis'],copy:'Exploring data flows, storage, and intelligent systems.'},{name:'FOUNDATIONS',items:['Java','Data Structures','Databases','Computer Networks'],copy:'The fundamentals behind connected software.'},{name:'TOOLS',items:['Git','Technical Documentation'],copy:'Versioned work and clear explanations.'}];
// Background supplied in the brief. Dates omitted; résumé not yet supplied.
export const education=[{title:'Computer Science & Engineering',subtitle:'B.Tech · Third-year student',detail:'Lendi Institute of Engineering and Technology'},{title:'Introduction to Internet of Things',subtitle:'NPTEL certification',detail:'Connected systems and their foundations'},{title:'Social Networks',subtitle:'NPTEL certification',detail:'Exploring relationships in connected systems'}];




